### ISSUE TITLE
Need for two requirements in "Address"

### ISSUE THREAD

**Issue by sandoche2k** [CENTRccTLDs/TRTF#58]
From reading the TRTF document, i understand that the document does not go into each minute requirements for a valid zone, but in turn gives an overall BCP. 

It might be a naive question. But, anyway better to ask :-). The first requirement in the "Address" category globally mentions the criteria for the type of IP addresses to be used in name servers. With this restriction in place, why do we need again to mention the specific categories such as bog-on?

**Comment by pawal** [comment]
Since both categories (allocated by RIR, and bogons) are SHOULD and SHOULD NOT, either could be used. Since you also have the caveat "not allocated to a RIR", checking that everything is allocated is tricky.

I would argue that it is up to the party that implements the requirement to chose the most proper methods. I do not feel strongly about the text about bogons, if you think it can be omitted I will be happy to remove it.
